[package]
name = "gns"
version = "0.1.0"
edition = "2021"
description = "Rust abstraction for Valve GameNetworkingSockets library."
license = "MIT / Apache-2.0"
repository = "https://github.com/hussein-aitlahcen/gns-rs"
authors = [ "Hussein Ait-Lahcen <hussein.aitlahcen@gmail.com> <https://github.com/hussein-aitlahcen>" ]
keywords = ["gamedev", "networking", "udp"]
categories = ["games"]

[dependencies]
gns-sys = { path = "../gns-sys" }
crossbeam-queue = "0.3"
either = "1.7"