[package]
name = "gns-sys"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for Valve GameNetworkingSockets library."
license = "MIT / Apache-2.0"
repository = "https://github.com/hussein-aitlahcen/gns-rs"
authors = [ "Hussein Ait-Lahcen <hussein@gmail.com> <https://github.com/hussein-aitlahcen>" ]
keywords = ["gamedev", "networking", "udp"]
categories = ["games"]

[lib]
crate-type = ["rlib", "staticlib"]

[build-dependencies]
bindgen = "0.69"
cc = { version = "1.1.31", features = ["parallel"] }