name: "Build"
on:
  push:
jobs:
  build-linux:
    name: Linux Debug
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: |
          nix develop -L --command bash -c "RUST_LOG=debug cargo build -p example -vvv"

  build-linux-release:
    name: Linux Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: |
          nix develop -L --command bash -c "RUST_LOG=debug cargo build -p example -vvv --release"

  build-windows:
    name: Windows Debug
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          $Env:RUST_LOG = "debug"
          cargo build -p example -vvv


  build-windows-release:
    name: Windows Release
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          $Env:RUST_LOG = "debug"
          cargo build -p example -vvv --release
