name: "Build"
on:
  push:
jobs:
  test-linux:
    name: Test - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: |
          nix develop -L --command bash -c "RUST_LOG=debug cargo test --workspace --exclude game-networking-sockets-sys"

  test-windows:
    name: Test - Windows
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          $Env:RUST_LOG = "debug"
          $Env:GNS_VCPKG_BUILDTREES_ROOT="$Env:GITHUB_WORKSPACE\vcpkg-buildtrees"
          cargo test --workspace --exclude game-networking-sockets-sys

  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: |
          nix develop -L --command bash -c "RUST_LOG=debug cargo build -p example -vvv"

  build-windows:
    name: Build - Windows
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: |
          $Env:RUST_LOG = "debug"
          $Env:GNS_VCPKG_BUILDTREES_ROOT="$Env:GITHUB_WORKSPACE\vcpkg-buildtrees"
          cargo build -p example -vvv
